<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "piment_config"
 *
 * Auto generated by Extension Builder 2017-11-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Piment Config',
	'description' => 'Configurations supplémentaires pour la plateforme TYPO3',
	'category' => 'be',
	'author' => '',
	'author_email' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '8.7.0-8.7.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);